//
// Created by Owner on 7/22/2024.
//

#ifndef PROJECT_2_SIMPLIFIED_PAGERANK_ALGORITHM_GRAPH_H
#define PROJECT_2_SIMPLIFIED_PAGERANK_ALGORITHM_GRAPH_H

#endif //PROJECT_2_SIMPLIFIED_PAGERANK_ALGORITHM_GRAPH_H
